### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by moutonrebelle** [moutonrebelle/ecommerce-pattern-library#2]
Hi @thomasjbradley

I have trouble seeing my product list page template, is there any reason why? 

Thanks,
Laura Meguerditchian

**Comment by thomasjbradley** [comment]
Try removing the quotes from `"candy"` on this line:
https://github.com/moutonrebelle/ecommerce-pattern-library/blob/master/products.html#L9

**Comment by moutonrebelle** [comment]
Just did and it's still not working.... @thomasjbradley

**Comment by thomasjbradley** [comment]
There’s a typo in this chunk of code—a `-` is missing. Copy & paste this to overwrite the code:
https://github.com/moutonrebelle/ecommerce-pattern-library/blob/master/_config.yml#L27-L31

```yml
defaults:
  - scope:
      path: _products
    values:
      layout: product
```
